/// Flutter icons Junaid
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Junaid
///      fonts:
///       - asset: fonts/Junaid.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Junaid {
  Junaid._();

  static const _kFontFam = 'Junaid';
  static const String? _kFontPkg = null;

  static const IconData spirtual = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasbih = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quran = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asma = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
