import 'package:junaid_jafferi/Model/rohani_model.dart';

class RohaniList {
  static List<RohnaiModel> list = [
    RohnaiModel(
      'assets/images/rohani/a.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/aa.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/b.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/bb.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/cc.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/d.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/e.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/ee.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/f.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/ff.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/g.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/gg.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/h.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/hh.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/i.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/ii.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/j.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/jj.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/k.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/l.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/m.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/n.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/nn.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/p.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/qq.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/r.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/rr.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/s.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/ss.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/t.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/tt.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/v.jpg',
    ),
    RohnaiModel(
      'assets/images/rohani/ww.jpg',
    ),
  ];
}
