import 'package:assets_audio_player/assets_audio_player.dart';

List<Audio> SurahList = [
  Audio.network('https://cdn.urdupoint.com/islam/quran/urdu/01-Al-Fatiha.mp3',
      metas: Metas(title: "Al-Fatiha", artist: " الفاتحة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/02-Al-Baqara.mp3",
      metas: Metas(title: "Al-Baqara", artist: " البقرة")),
  Audio.network('https://cdn.urdupoint.com/islam/quran/urdu/03-Aal-e-Imran.mp3',
      metas: Metas(title: "Aal-e-Imran", artist: ' آل عمران')),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/04-An-Nisa.mp3",
      metas: Metas(title: "An-Nisa", artist: "  النساء")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/05-Maidah.mp3",
      metas: Metas(title: "Maidah", artist: " المائدة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/06-Al-Anam.mp3",
      metas: Metas(
        title: "Al-An'am",
        artist: "لأنعام",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/07-Al-Araf.mp3",
      metas: Metas(title: "Al-A'raf", artist: " الأعراف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/08-Al-Anfal.mp3",
      metas: Metas(title: "Al-Anfal", artist: " الأنفال")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/09-Taubah.mp3",
      metas: Metas(title: "Taubah", artist: "  التوبة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/10-Yunus.mp3",
      metas: Metas(title: "Yunus", artist: " يونس ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/11-Hud.mp3",
      metas: Metas(title: "Hud", artist: " هود")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/12-Yusuf.mp3",
      metas: Metas(title: "Yusuf", artist: "يوسف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/13-Ar-Rad.mp3",
      metas: Metas(title: "Ar-Ra'd", artist: " الرعد")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/14-Ibrahim.mp3",
      metas: Metas(title: "Ibrahim", artist: " إبراهيم")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/15-Al-Hijr.mp3",
      metas: Metas(title: "Al-Hijr", artist: "  الحجر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/16-An-Nahl.mp3",
      metas: Metas(title: "An-Nahl", artist: " النحل ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/17-Al-Isra.mp3",
      metas: Metas(title: "Al-Isra", artist: "الإسراء")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/18-Al-Kahf.mp3",
      metas: Metas(title: "Al-Kahf", artist: " الكهف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/19-Maryam.mp3",
      metas: Metas(
        title: "Maryam",
        artist: " مريم",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/20-Taha.mp3",
      metas: Metas(
        title: "Taha",
        artist: "طه",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/21-Al-Anbiya.mp3",
      metas: Metas(title: "Al-Anbiya", artist: "   الأنبياء")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/22-Al-Hajj.mp3",
      metas: Metas(title: "Al-Hajj", artist: " الحج ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/23-Al-Muminun.mp3",
      metas: Metas(title: "Al-Mu'minun", artist: "المؤمنون")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/24-An-Noor.mp3",
      metas: Metas(title: "An-Nur", artist: " النور")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/25-Al-Furqan.mp3",
      metas: Metas(title: "Al-Furqan", artist: " الفرقان")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/26-Ash-Shuara.mp3",
      metas: Metas(title: "Al-Shuara", artist: " الشعراء")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/27-An-Naml.mp3",
      metas: Metas(title: "An-Naml", artist: "النمل")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/28-Al-Qasas.mp3",
      metas: Metas(title: "Al-Qasas", artist: "  القصص ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/29-Al-Ankabut.mp3",
      metas: Metas(title: "Al-Ankabut", artist: "العنكبوت")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/30-Ar-Rum.mp3",
      metas: Metas(title: "Surah Ar-Rum", artist: "الروم")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/31-Luqman.mp3",
      metas: Metas(title: "Luqman", artist: "لقمان")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/32-As-Sajdah.mp3",
      metas: Metas(title: "As-Sajdah", artist: "السجدة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/33-Al-Ahzab.mp3",
      metas: Metas(title: "Al-Ahzab", artist: "الأحزاب")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/34-Saba.mp3",
      metas: Metas(title: "Saba", artist: "سبأ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/35-Fatir.mp3",
      metas: Metas(title: "Fatir", artist: "فاطر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/36-Yaseen.mp3",
      metas: Metas(title: "Yaseen", artist: "يس")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/37-As-Saffat.mp3",
      metas: Metas(title: "Al-Safaat", artist: "الصافات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/38-Sad.mp3",
      metas: Metas(title: "Sad", artist: "ص")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/39-Az-Zumar.mp3",
      metas: Metas(title: "Az-Zumar", artist: "الزمر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/40-Ghafir.mp3",
      metas: Metas(title: "Ghafir", artist: "غافر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/41-Fussilat.mp3",
      metas: Metas(title: "Fussilat", artist: "فصلت")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/42-Ash-Shura.mp3",
      metas: Metas(title: "Ash-Shura", artist: "الشورى")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/43-Az-Zukhruf.mp3",
      metas: Metas(title: "Az-Zukhruf", artist: "الزخرف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/44-Ad-Dukhan.mp3",
      metas: Metas(title: "Ad-Dukhan", artist: "الدخان")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/45-Al-Jathiyah.mp3",
      metas: Metas(title: "Al-Jathiyah", artist: "الجاثية")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/46-Al-Ahqaf.mp3",
      metas: Metas(title: "Al-Ahqaf", artist: "الأحقاف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/47-Muhammad.mp3",
      metas: Metas(title: "Muhammad", artist: "محمد")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/48-Al-Fath.mp3",
      metas: Metas(title: "Al-Fath", artist: "الفتح")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/49-Al-Hujurat.mp3",
      metas: Metas(title: "Al-Hujurat", artist: "الحجرات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/50-Qaf.mp3",
      metas: Metas(title: "Qaf", artist: "ق")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/51-Adh-Dhariyat.mp3",
      metas: Metas(title: "Adh-Dhariyat", artist: "الذاريات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/52-At-Tur.mp3",
      metas: Metas(title: "At-Tur", artist: "الطور")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/53-An-Najm.mp3",
      metas: Metas(
        title: "An-Najm",
        artist: "النجم",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/54-Al-Qamar.mp3",
      metas: Metas(
        title: "Al-Qamar",
        artist: "القمر",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/55-Ar-Rahman.mp3",
      metas: Metas(
        title: "Ar-Rahman",
        artist: "الرحمن",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/56-Waqiah.mp3",
      metas: Metas(
        title: "Waqiah",
        artist: "الواقعة",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/57-Al-Hadid.mp3",
      metas: Metas(
        title: "Al-Hadid",
        artist: "الحديد",
      )),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/58-Al-Mujadilah.mp3",
      metas: Metas(
        title: "Al-Mujadilah",
        artist: "المجادلة",
      )),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/59-Al-Hashr.mp3",
      metas: Metas(title: "Al-Hashr", artist: "الحشر")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/60-Al-Mumtahanah.mp3",
      metas: Metas(title: "Al-Mumtahanah", artist: "الممتحنة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/61-As-Saff.mp3",
      metas: Metas(title: "Al-Saff", artist: "الصف")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/62-Al-Jumu'ah.mp3",
      metas: Metas(title: "Al-Jumu'ah", artist: "الجمعة")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/63-Al-Munafiqun.mp3",
      metas: Metas(title: "Al-Munafiqun", artist: "المنافقون")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/64-At-Taghabun.mp3",
      metas: Metas(title: "At-Taghabun", artist: "التغابن")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/65-At-Talaq.mp3",
      metas: Metas(title: "At-Talaq", artist: "الطلاق")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/66-At-Tahrim.mp3",
      metas: Metas(title: "At-Tahrim", artist: "التحريم")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/67-Al-Mulk.mp3",
      metas: Metas(title: "Al-Mulk", artist: "الملك")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/68-Al-Qalam.mp3",
      metas: Metas(title: "Al-Qalam", artist: "القلم")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/69-Al-Haaqqah.mp3",
      metas: Metas(title: "Al-Haaqqah", artist: "الحاقة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/70-Al-Ma'arij.mp3",
      metas: Metas(title: "Al-Ma'arij", artist: "المعارج")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/71-Nooh.mp3",
      metas: Metas(title: "Nooh", artist: "نوح")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/72-Al-Jinn.mp3",
      metas: Metas(title: "Al-Jinn", artist: "الجن")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/73-Al-Muzzammil.mp3",
      metas: Metas(title: "Al-Muzzammil", artist: "المزمل")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/74-Al-Muddaththir.mp3",
      metas: Metas(title: "Al-Muddathsir", artist: "المدثر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/75-Al-Qiyamah.mp3",
      metas: Metas(title: "Al-Qiyamah", artist: "القيامة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/76-Al-Insan.mp3",
      metas: Metas(title: "Al-Insan", artist: "الإنسان")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/77-Al-Mursalat.mp3",
      metas: Metas(title: "Al-Mursalat", artist: "المرسلات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/78-An-Naba.mp3",
      metas: Metas(title: "An-Naba", artist: "النبأ")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/79-An-Naziat.mp3",
      metas: Metas(title: "An-Nazi'at", artist: "النازعات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/80-Abasa.mp3",
      metas: Metas(title: "Abasa", artist: "عبس")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/81-At-Takwir.mp3",
      metas: Metas(title: "At-Takwir", artist: "التكوير")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/82-Al-Infitar.mp3",
      metas: Metas(title: "Al-Infita", artist: "الانفطار")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/83-Al-Mutaffifin.mp3",
      metas: Metas(title: "Al-Mutaffifin", artist: "المطففين")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/84-Al-Inshiqaq.mp3",
      metas: Metas(title: "Al-Inshiqaq", artist: "الانشقاق")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/85-Al-Buruj.mp3",
      metas: Metas(title: "Al-Buruj", artist: "البروج")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/86-At-Tariq.mp3",
      metas: Metas(title: "At-Tariq", artist: "الطارق")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/87-Al-Ala.mp3",
      metas: Metas(title: "Al-A'la", artist: "الأعلى")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/88-Al-Ghashiya.mp3",
      metas: Metas(title: "Al-Ghashiya", artist: "الغاشية")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/89-Al-Fajr.mp3",
      metas: Metas(title: "Al-Fajr", artist: "الفجر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/90-Al-Balad.mp3",
      metas: Metas(title: "Al-Balad", artist: "البلد")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/91-Ash-Shams.mp3",
      metas: Metas(title: "Ash-Shams", artist: "الشمس")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/92-Al-Layl.mp3",
      metas: Metas(title: "Al-Layl", artist: "الليل")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/93-Ad-Duha.mp3",
      metas: Metas(title: "Ad-Duha", artist: "الضحى")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/94-As-Sharh.mp3",
      metas: Metas(title: "As-Sharh", artist: "الشرح")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/95-At-Tin.mp3",
      metas: Metas(title: "At-Tin", artist: "التين")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/96-Al-alaq.mp3",
      metas: Metas(title: "Al-'alaq", artist: "العلق")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/97-Al-Qadr.mp3",
      metas: Metas(title: "Al-Qadr", artist: "القدر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/98-Al-Bayyinah.mp3",
      metas: Metas(title: "Al-Bayyinah", artist: "البينة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/99-Az-Zalzalah.mp3",
      metas: Metas(title: "Az-Zalzalah", artist: "الزلزلة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/100-Al-adiyat.mp3",
      metas: Metas(title: "Al-'adiyat", artist: "العاديات")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/101-Al-Qaria.mp3",
      metas: Metas(title: "Al-Qari'a", artist: "القارعة")),
  Audio.network(
      "https://cdn.urdupoint.com/islam/quran/urdu/102-At-Takathur.mp3",
      metas: Metas(title: "At-Takathur", artist: "التكاثر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/103-Al-Asr.mp3",
      metas: Metas(title: "Al-Asr", artist: "العصر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/104-Al-Humazah.mp3",
      metas: Metas(title: "Al-Humazah", artist: "الهمزة")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/105-Al-Fil.mp3",
      metas: Metas(title: "Al-Fial", artist: "الفيل")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/106-Quraish.mp3",
      metas: Metas(title: "Quraish", artist: "قريش")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/107-Al-Maun.mp3",
      metas: Metas(title: "Al-Ma'un", artist: "الماعون")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/108-Al-Kauthar.mp3",
      metas: Metas(title: "Al-Kauthar", artist: "الكوثر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/109-Al-Kafirun.mp3",
      metas: Metas(title: "Al-Kafirun", artist: "الكافرون")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/110-An-Nasr.mp3",
      metas: Metas(title: "An-Nasr", artist: "النصر")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/111-Al-Masad.mp3",
      metas: Metas(title: "Al-Masad", artist: "المسد")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/112-Al-Ikhlas.mp3",
      metas: Metas(title: "Al-Ikhlas", artist: "الإخلاص")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/113-Al-Falaq.mp3",
      metas: Metas(title: "Al-Falaq", artist: "الفلق")),
  Audio.network("https://cdn.urdupoint.com/islam/quran/urdu/114-An-Nas.mp3",
      metas: Metas(title: "An-Nas", artist: "الناس")),
];
